version = 0.1

[default.global.parameters]
stack_name = "TaskHandlers"

[default.deploy]
[default.deploy.parameters]
confirm_changeset = false
capabilities = "CAPABILITY_IAM"
s3_prefix = "task-handlers"
region = "eu-west-1"
