# More information about the configuration file can be found here:
# https://docs.aws.amazon.com/serverless-application-model/latest/developerguide/serverless-sam-cli-config.html
version = 0.1

[default]
[default.global.parameters]
stack_name = "eventbridge-momento-testing"

[default.validate.parameters]
lint = true

[default.deploy.parameters]
capabilities = "CAPABILITY_IAM"
confirm_changeset = false
resolve_s3 = true

[momento]
[momento.global.parameters]
stack_name = "eventbridge-momento-testing-momento"

[momento.build.parameters]
template_file = "template-momento.yaml"

[momento.validate.parameters]
lint = true

[momento.deploy.parameters]
capabilities = "CAPABILITY_IAM"
confirm_changeset = false
resolve_s3 = true

