AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Sample application to test EventBridge with Momento Topics

Globals:
  Function:
    Timeout: 30

Resources:
  MyFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: src/handlers/
      Handler: my-function.handler
      Runtime: nodejs18.x
      Architectures:
        - x86_64
      Environment:
        Variables:
          EVENT_BUS: !Ref EventBus
      Policies:
        - EventBridgePutEventsPolicy:
            EventBusName: !Ref EventBus
      Events:
        Api:
          Type: Api
          Properties:
            Path: /
            Method: get
    Metadata:
      BuildMethod: esbuild
      BuildProperties:
        Minify: true
        Target: 'es2020'
        Sourcemap: true
        EntryPoints:
          - my-function.ts
  EventBus:
    Type: AWS::Events::EventBus
    Properties:
      Name: !Sub ${AWS::StackName}-event-bus
  DebugLogGroup:
    Type: AWS::Logs::LogGroup
    Properties:
      LogGroupName: !Sub /aws/events/${AWS::StackName}-event-bus-debug
      RetentionInDays: 1
  DebugRule:
    Type: AWS::Events::Rule
    Properties:
      Name: !Sub ${AWS::StackName}-debug-rule
      Description: Rule to debug events
      EventBusName: !Ref EventBus
      EventPattern:
        source:
          - prefix: ''
      Targets:
        - Arn: !GetAtt DebugLogGroup.Arn
          Id: !Sub ${AWS::StackName}-debug-target

Outputs:
  ApiUrl:
    Description: 'API Gateway endpoint URL'
    Value: !Sub 'https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/'
