AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Sample application

Globals:
  Function:
    Timeout: 30

Resources:
  CreateOrder:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: src/handlers/
      Handler: create-order.handler
      Runtime: nodejs18.x
      Architectures:
        - x86_64
      Environment:
        Variables:
          EVENT_BUS: !Ref EventBus
      Policies:
        - EventBridgePutEventsPolicy:
            EventBusName: !Ref EventBus
      Events:
        Api:
          Type: Api
          Properties:
            Path: /
            Method: post
    Metadata:
      BuildMethod: esbuild
      BuildProperties:
        Minify: true
        Target: 'es2020'
        Sourcemap: true
        EntryPoints:
          - create-order.ts

  EventBus:
    Type: AWS::Events::EventBus
    Properties:
      Name: !Sub ${AWS::StackName}-event-bus

Outputs:
  ApiUrl:
    Description: 'API Gateway Endpoint URL'
    Value: !Sub 'https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/'
  EventBusName:
    Description: 'Event Bus Name'
    Value: !Ref EventBus
    Export:
      Name: !Sub MyEventBusName
