version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "sam-export"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-1a8v2k18shfkm"
s3_prefix = "sam-export"
region = "eu-west-1"
capabilities = "CAPABILITY_IAM"
image_repositories = []
