version = 0.1

[default.global.parameters]
stack_name = "TaskAPI"

[default.deploy]
[default.deploy.parameters]
confirm_changeset = false
capabilities = "CAPABILITY_IAM"
s3_prefix = "task-api"
region = "eu-west-1"
