AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31
Description: Example app showcasing how to mock HTTP APIs with WireMock

Parameters:
  AnotherServiceUrl:
    Type: String
  WiremockExtensionArn:
    Type: String
    Default: ""
    Description: "ARN of the Wiremock Lambda Extension layer. If not provided, the extension will not be used."

Conditions:
  HasWiremockExtension:
    Fn::Not:
      - Fn::Equals:
        - !Ref WiremockExtensionArn
        - ""

Resources:
  StubsLayer:
    Condition: HasWiremockExtension
    Type: AWS::Serverless::LayerVersion
    Properties:
      ContentUri: wiremock
      CompatibleRuntimes:
        - nodejs22.x

  ApiFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: src/functions/api.handler
      Runtime: nodejs22.x
      Architectures:
        - arm64
      Timeout: 30
      Layers: !If
        - HasWiremockExtension
        - - !Ref WiremockExtensionArn
          - !Ref StubsLayer
        - !Ref AWS::NoValue
      Environment:
        Variables:
          ANOTHER_SERVICE_URL: !Ref AnotherServiceUrl
      Events:
        HelloApi:
          Type: HttpApi
          Properties:
            Path: /hello
            Method: get
    Metadata:
      BuildMethod: esbuild
      BuildProperties:
        Minify: true
        Target: "es2020"
        Sourcemap: true

Outputs:
  ApiURL:
    Description: "API Gateway endpoint URL"
    Value: !Sub "https://${ServerlessHttpApi}.execute-api.${AWS::Region}.amazonaws.com"
